[package]
name = "electrs"
version = "0.10.0"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/romanz/electrs"
repository = "https://github.com/romanz/electrs"
keywords = ["bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2021"
build = "build.rs"

[features]
default = ["metrics"]
metrics = ["prometheus", "tiny_http"]
metrics_process = ["prometheus/process"]
http = ["axum", "tower-http"]

[package.metadata.configure_me]
spec = "internal/config_specification.toml"

[dependencies]
anyhow = "1.0"
axum = { version = "0.6.17", features = ["headers", "macros"], optional = true }
bitcoin = { version = "0.30.0", features = ["serde", "rand-std"] }
bitcoincore-rpc = "0.17.0"
configure_me = "0.4"
crossbeam-channel = "0.5"
dirs-next = "2.0"
env_logger = "0.10"
log = "0.4"
parking_lot = "0.12"
prometheus = { version = "0.13", optional = true }
rayon = "1.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
signal-hook = "0.3"
tokio = { version = "1.28.2", features = ["full"] }
tower-http = { version = "0.4.0", features = ["cors"], optional = true }
tiny_http = { version = "0.12", optional = true }

[dependencies.electrs-rocksdb]
version = "0.19.0-e2"

default-features = false
# ZSTD is used for data compression
# Snappy is only for checking old DB
features = ["zstd", "snappy"]

[build-dependencies]
configure_me_codegen = { version = "0.4.4", default-features = false }

[dev-dependencies]
hex_lit = "0.1.1"
tempfile = "3.5"
